file="../../nextnew/PMondriaan/test/data/matrices/Emilia_923/Emilia_923.mtx"
fix-file="./pmon0003fix2.txt"
processors=1
parts=2
eps=0.04
eta=0.03
weights="degree"
bisect=1
sampling=0
metric=1
sample_size=10000
max_cluster_size=50
lp_max_iter=25
coarsening_nrvertices=200
coarsening_max_rounds=128
KLFM_max_passes=25
KLFM_max_no_gain_moves=200
KLFM_par_send_moves=20
